### ISSUE TITLE
Autoremove expired locks

### ISSUE THREAD

**Issue by antonio-osorio** [lorehov/mongolock#5]
After a lock has expired a document with:

```
{ "_id" : "key" , "owner" :  null  , "expire" :  null  , "locked" : false , "created" :  null }
```

is left in the database. This is ok when the keys are static, but when they are dynamic, this leads to large number of unnecessary documents left behind.

It would be great to have an option to autoremove the record when releasing the lock

**Comment by lorehov** [comment]
@antonio-osorio seems like it is possible to clean lock collection even without autoremove option. You can use mongo TTL collections, in that case you can just pass collection=my_lock_collection_with_ttl to MongoLock constructor. 
For example:
```
from pymongo import MongoClient
from mongolock import MongoLock

my_lock_collection = MongoClient().my_db.my_lock_collection
my_lock_collection.create_index('created', expireAfterSeconds=3600*24)

with MongoLock(collection=my_lock_collection) as lock:
    # do some staff
```

But if this solution is not suitable for you - we can introduce`autoremove=True` option to `lock` and `__call__` methods signature. Please let me know if it is the case.

**Comment by antonio-osorio** [comment]
@lorehov I was not aware of Mongo's TTL feature on collections. That takes care of my use case, thanks!
